lucene:
  dbpath: d:\Users\cuiyingfan\Desktop\Medicom\MCDEX\mcdex_raw.db
  indexpath: d:\Users\cuiyingfan\Desktop\Medicom\MCDEX\index
spring:
  datasource:
    url: jdbc:p6spy:sqlite:${lucene.dbpath}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username:
    password:
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html

logging:
  level: debug
  level.com.dalianpai: debug
  file:
    path: logs:/
server:
  port: 10086
